meta:
  engine: 4.1.0
units:
  # Shift Variable
  sv: 0.2
  # Proxy Spacing Variables
  kx: cx # 18 mm width
  ky: cy # 17 mm height
  # Padding Variables
  px: kx + 2
  py: ky + 2
  # Controller Variables
  mcu_height: 34
  mcu_width: 18
  mcu_padding: 1.5
  # Misc Variables
  rst_height: 8.6
  rst_width: 5.8
  rst_padding: 2.7 # center to edge
points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      anchor.shift: [50,-100] # Fix KiCad placement
      columns:
        outer:
        pinky:
          key.stagger: 0.1cx
        ring:
          key.stagger: 0.66cx
        middle:
          key.stagger: 0.25cx
        index:
          key.stagger: -0.25cx
        inner:
          key.stagger: -0.15cx
      rows:
        bottom:
        home:
        top:
    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_index_bottom
        shift: [0, -1.25cx]
      columns:
        tuck:
          key.name: thumb_tuck
          key.shift: [-0.34cx, 0.14cx]
        layer: 
          key.name: thumb_layer
          key.shift: [-0.25cx, 0]
          key.splay: -10
        space:
          key.name: thumb_space
          key.width: 1.5kx
          key.shift: [-0.15cx, 0.13cx]
          key.rotate: -90
          key.splay: -10
        reach:
          key.name: thumb_reach
          key.width: 1.5kx
          key.shift: [-0.04cx, 0.03cx]
          key.rotate: -90
          key.splay: -10
      rows:
        cluster:
  mirror: &mirror
    distance: 22kx
outlines:
    raw:
    - what: rectangle
      where: true
      size: [px, py]
    master_keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
    - what: rectangle
      where: [thumb_space, thumb_reach]
      size: [1.5kx,ky]
    mirror_thumb_keys:
    - what: rectangle
      where: [mirror_thumb_space, mirror_thumb_reach]
      size: [1.5kx, ky]
    master:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_top
          shift: [-0.5px, 0.7py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [0.5px, 0.5py]
        - ref: matrix_index_top
          shift: [0.5px, 0.6py]
        - ref: matrix_inner_top
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px+mcu_padding+mcu_width+0.25, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px+mcu_padding+mcu_width+0.25, -0.5py]
        - ref: matrix_inner_bottom
          shift: [0.5px+mcu_padding+mcu_width+0.25, -0.5py]      
        - ref: thumb_reach
          shift: [-0.8kx, -0.5py]
        - ref: thumb_reach
          shift: [-0.8kx, 0.5py]
        - ref: thumb_reach
          shift: [0.8kx, 0.5py]        
        - ref: thumb_space
          shift: [0.8kx, 0.5py]
        - ref: thumb_space
          shift: [0.8kx, -0.5py]          
        - ref: thumb_layer
          shift: [-0.5px,-0.5py]                    
        - ref: thumb_tuck
          shift: [-0.5px,-0.5py]               
        - ref: matrix_pinky_bottom
          shift: [0.5px,-0.6py]                                      
        - ref: matrix_outer_bottom
          shift: [-0.5px,-0.5py]
    slave:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_outer_bottom
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_pinky_bottom
          shift: [0.5px, -0.6py]
        - ref: mirror_thumb_tuck
          shift: [-0.5px, -0.5py]
        - ref: mirror_thumb_layer
          shift: [-0.5px, -0.5py]
        - ref: mirror_thumb_space
          shift: [0.8kx, -0.5py]
        - ref: mirror_thumb_space
          shift: [0.8kx, 0.5py]
        - ref: mirror_thumb_reach
          shift: [0.8kx, 0.5py]
        - ref: mirror_thumb_reach
          shift: [-0.8kx, 0.5py]
        - ref: mirror_thumb_reach
          shift: [-0.8kx, -0.5py]
        - ref: mirror_matrix_inner_bottom
          shift: [0.5px+mcu_padding+mcu_width+0.25, -0.5py]
        - ref: mirror_matrix_inner_top
          shift: [0.5px+mcu_padding+mcu_width+0.25, -0.5py]
        - ref: mirror_matrix_inner_top
          shift: [0.5px+mcu_padding+mcu_width+0.25, 0.5py]
        - ref: mirror_matrix_inner_top
          shift: [0.5px, 0.5py]
        - ref: mirror_matrix_index_top
          shift: [0.5px, 0.6py]
        - ref: mirror_matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_pinky_top
          shift: [-0.5px, 0.7py]
        - ref: mirror_matrix_outer_top
          shift: [-0.5px, 0.5py]
    mcu_outline:
    - what: rectangle
      where:
        ref: matrix_inner_top
        shift: [kx+mcu_padding, -mcu_width/2-0.3]
        rotate: -90
      size: [mcu_height, mcu_width]
    mirror_mcu_outline:
    - what: rectangle
      where:
        ref: mirror_matrix_inner_top
        shift: [kx+mcu_padding, -mcu_width/2-0.3]
        rotate: -270
      size: [mcu_height, mcu_width]
    rst_outline:
    - what: rectangle
      where:
        ref: matrix_inner_bottom
        shift: [0.5px+mcu_padding+mcu_width+0.25-rst_padding-sv, 3]
        rotate: -270
      size: [rst_height, rst_width]
    mirror_rst_outline:
    - what: rectangle
      where:
        ref: mirror_matrix_inner_bottom
        shift: [0.5px+mcu_padding+mcu_width+0.25-rst_padding-sv, 3]
        rotate: -270
      size: [rst_height, rst_width]   
    combo:
     - name: master
     - operation: add
       name: master_keys
     - name: slave
     - operation: subtract
       name: master_keys
     - operation: subtract
       name: mirror_thumb_keys
     - name: mcu_outline
       operation: subtract
     - name: mirror_mcu_outline
       operation: subtract
     - name: rst_outline
       operation: subtract   
     - name: mirror_rst_outline
       operation: subtract           
pcbs:
  keyboard:
    outlines.main.outline: combo
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      mcu_l:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: matrix_inner_top
          shift: [kx+mcu_padding, -mcu_width/2-0.3]
          rotate: -90
      mcu_r:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: mirror_matrix_inner_top
          shift: [kx+mcu_padding, -mcu_width/2-0.3]
          rotate: -270
      rst_l:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: matrix_inner_bottom
          shift: [0.5px+mcu_padding+mcu_width+0.25-rst_padding-sv, 3]
          rotate: -90
      rst_r:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: mirror_matrix_inner_bottom
          shift: [0.5px+mcu_padding+mcu_width+0.25-rst_padding-sv, 3]
          rotate: -90