meta:
  engine: 4.1.0
  name: scyboard
  version: 1.0
  author: Scybin
  url: https://github.com/Scybin/scyboard
units:
  # Key Variables
  kx: cx # 18 mm width
  ky: cy # 17 mm height
  px: kx + 2 # horizontal padding (20mm)
  py: ky + 2 # vertical padding (19mm)
  ks: 18.5 # horizontal space between columns (default: 19)
  kp: 17.5 # vertical padding between keys (deafult: 19)
  kcow: 13.8 # key cutout hole width (cherry, choc v2: 14, choc v1: 13.8)
  kcoh: 13.8 # key cutout hole height (cherry, choc v2: 14, choc v1: 13.8)
  keycw: 17.5 # keycap width (cherry: 18, choc: 17.5)
  keych: 16.5 # keycap height (cherry: 18, choc: 16.5)  
  vertical_diode_shift: 1.5 # How much to shift to avoid overlap
  horizontal_diode_shift: -0.5 kcow - 0.85
  diode_rotation: -180 # Diode rotation
  switch_rotation: 180 # Hotswap south, led north
  # Physical measures
  screw_radius: 1.1 # M2 screws
  screw_diameter: screw_radius * 2
  screw_head_radius: 2.05
  screw_head_diameter: screw_head_radius * 2
  spacer_radius: 2.15 # M2 standoffs
  spacer_diameter: spacer_radius * 2
  fillet_radius: 0.5
  pwr_trace_width: 0.25
  gnd_trace_width: 0.25
  signal_trace_width: 0.15
  via_size: 0.56 # JLCPCB min 0.56 | KiCad default 0.8
  via_drill: 0.3 # JLCPCB min 0.3 | KiCad default 0.4
  # Controller Variables
  mcu_height: 33
  mcu_width: 18
  mcu_padding: 1.5
points:
  zones:
    matrix:
      key:
        padding: ky
        spread: kx
      anchor.shift: [50,-100] # Fix KiCad placement
      columns:
        outer:
          key:
            column_net: C0
        pinky:
          key:
            column_net: C1
            stagger: 0.1cx
        ring:
          key:
            column_net: C2
            stagger: 0.66cx
        middle:
          key:
            column_net: C3
            stagger: 0.25cx
        index:
          key:
            column_net: C4
            stagger: -0.25cx
        inner:
          key:
            column_net: C5
            stagger: -0.15cx
      rows:
        bottom:
          row_net: R2
        home:
          row_net: R1
        top:
          row_net: R0
    thumb:
      key:
        padding: ky
        spread: kx
      anchor:
        ref: matrix_index_bottom
        shift: [0, -1.25cx]
      columns:
        tuck:
          key:
            column_net: C2
            name: thumb_tuck
            shift: [-0.34cx, 0.14cx]
        layer: 
          key:
            column_net: C3
            name: thumb_layer
            shift: [-0.25cx, 0]
            splay: -10
        space:
          key:
            column_net: C4
            name: thumb_space
            width: 1.5kx
            shift: [-0.15cx, 0.13cx]
            rotate: -90
            splay: -10
        reach:
          key:
           column_net: C5
           name: thumb_reach
           width: 1.5kx
           shift: [-0.04cx, 0.03cx]
           rotate: -90
           splay: -10
      rows:
        cluster:
          row_net: R3
outlines:
    raw:
    - what: rectangle
      where: true
      size: [px, py]
    keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
    - what: rectangle
      where: [thumb_space, thumb_reach]
      size: [1.5kx,ky]
    master:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_top
          shift: [-0.5px, 0.7py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [0.5px, 0.5py]
        - ref: matrix_index_top
          shift: [0.5px, 0.6py]
        - ref: matrix_inner_top
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px+mcu_padding+mcu_width+0.25, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px+mcu_padding+mcu_width+0.25, -0.5py]
        - ref: matrix_inner_bottom
          shift: [0.5px+mcu_padding+mcu_width+0.25, -0.5py]      
        - ref: thumb_reach
          shift: [-0.8kx, -0.5py]
        - ref: thumb_reach
          shift: [-0.8kx, 0.5py]
        - ref: thumb_reach
          shift: [0.8kx, 0.5py]        
        - ref: thumb_space
          shift: [0.8kx, 0.5py]
        - ref: thumb_space
          shift: [0.8kx, -0.5py]          
        - ref: thumb_layer
          shift: [-0.5px,-0.5py]                    
        - ref: thumb_tuck
          shift: [-0.5px,-0.5py]               
        - ref: matrix_pinky_bottom
          shift: [0.5px,-0.6py]                                      
        - ref: matrix_outer_bottom
          shift: [-0.5px,-0.5py]
    mcu_outline:
    - what: rectangle
      where:
        ref: matrix_inner_top
        shift: [kx+mcu_padding, -mcu_width/2+mcu_padding-0.5]
        rotate: -90
      size: [mcu_height, mcu_width]
    combo:
     - name: master
     - operation: add
       name: keys
pcbs:
  keyboard:
    template: kicad8
    outlines:
      main:
        outline: combo
    footprints:
      key_switches_b:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          hotswap: true
          reversible: false
          from: "{{column_net}}"
          to: "{{colrow}}_B"
          side: B
        adjust:
          rotate: switch_rotation
      diodes_b:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}_B"
          to: "{{row_net}}"
          include_tht: false
          reversible: false
          side: B
        adjust:
          shift: [horizontal_diode_shift,vertical_diode_shift]
          rotate: 90 + diode_rotation
      key_switches_f:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          hotswap: true
          reversible: false
          from: "{{column_net}}"
          to: "{{colrow}}_F"
          side: F
        adjust:
          rotate: switch_rotation
      diodes_f:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}_F"
          to: "{{row_net}}"
          include_tht: false
          reversible: false
          side: F
        adjust:
          shift: [-1 * horizontal_diode_shift,vertical_diode_shift]
          rotate: 90 + diode_rotation         
      mcu:
        what: ceoloide/mcu_nice_nano
        where:
          ref: matrix_inner_top
          shift: [kx+mcu_padding, -mcu_width/2-0.3]
        params:
          P0: DAT
          P1: LED
          P21: C0
          P20: C1
          P19: C2
          P18: C3
          P15: C4
          P14: C5
          P2: SDA
          P3: SCL
          P4: CS
          P5: R0
          P6: R1
          P7: R2
          P8: R3
          reversible: true
          include_traces: true
          show_silk_labels: true
          show_via_labels: true
          show_instructions: false
          use_rectangular_jumpers: true
      on_off_switch:
        what: ceoloide/power_switch_smd_side
        where: matrix_inner_top
        params:
          from: BAT_P
          to: RAW
          reversible: true
        adjust:
          shift: [1.5 ks -0.5, 0.375 kp -46.50]
      reset_switch:
        what: ceoloide/reset_switch_smd_side
        where: matrix_inner_top
        params:
          from: GND
          to: RST
          reversible: true
          include_bosses: true
        adjust:
          shift: [19.704, 0.24 kp - 0.1]    
      battery_connector:  
        what: ceoloide/battery_connector_jst_ph_2
        where: matrix_inner_top
        params:
          BAT_P: BAT_P
          BAT_N: GND
          reversible: true
          include_courtyard: false
        adjust:
          shift: [0.5 ks + 7.25, 0.375 kp -45.25]
          rotate: 90                
      