meta:
  engine: 4.1.0
units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2
points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      anchor.shift: [50,-100] # Fix KiCad placement
      columns:
        outer:
        pinky:
          key.stagger: 0.1cx
        ring:
          key.stagger: 0.66cx
        middle:
          key.stagger: 0.25cx
        index:
          key.stagger: -0.25cx
        inner:
          key.stagger: -0.15cx
      rows:
        bottom:
        home:
        top:
    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_index_bottom
        shift: [0, -1.25cx]
      columns:
        tuck:
          key.name: thumb_tuck
          key.shift: [-0.34cx, 0.14cx]
        layer: 
          key.name: thumb_layer
          key.shift: [-0.25cx, -0cx]
          key.splay: -10
        space:
          key.name: thumb_space
          key.width: 1.5kx
          key.shift: [-0.15cx, 0.13cx]
          key.rotate: -90
          key.splay: -10
        reach:
          key.name: thumb_reach
          key.width: 1.5kx
          key.shift: [-0.04cx, 0.03cx]
          key.rotate: -90
          key.splay: -10
  mirror: &mirror
    distance: 22kx
outlines:
    raw:
    - what: rectangle
      where: true
      size: [px, py]
    keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
    board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [0, 0]
