meta:
  engine: 4.1.0
  name: scyboard
  version: 1.0
  author: Scybin
  url: https://github.com/Scybin/scyboard

units:

  # Key Variables
  kx: cx # 18 mm width
  ky: cy # 17 mm height
  px: kx + 2 # horizontal padding (20mm)
  py: ky + 2 # vertical padding (19mm)
  ks: 18.5 # horizontal space between columns (default: 19)
  kp: 17.5 # vertical padding between keys (deafult: 19)
  kcow: 13.8 # key cutout hole width
  kcoh: 13.8 # key cutout hole height
  keycw: 17.5 # keycap width (cherry: 18, choc: 17.5)
  keych: 16.5 # keycap height (cherry: 18, choc: 16.5)  
  switch_rotation: 180 # Hotswap south, led north

  # Diode Variables
  vertical_diode_shift: 1.5 # How much to shift to avoid overlap
  horizontal_diode_shift: -0.5 kcow - 0.85
  diode_rotation: -180 # Diode rotation

  # Controller Variables
  mcu_width: 18 # x-axis
  mcu_height: 33 # y-axis
  mcu_padding: 1.5

  # Reset Switch Variables
  rst_x: 27.884 # Reset switch position on x-axis
  rst_y: -28.5 # Reset switch position on y-axis

  # On Off Switch Variables
  pwr_x: 27.725 # On off switch position on x-axis
  pwr_y: rst_y-9.35 # On off switch position on y-axis

  # JST Variables
  jst_x: pwr_x-4.5 # JST connector position on x-axis
  jst_y: -34.01 # JST connector position on y-axis
  jst_shift: 3.5 # JST footprint center point shift

  # Screw variables
  screw_size: 1.5 # M2 flathead screw
  screw_x: (-kx/2) # Screw position on x-axis
  screw_y: (-ky/2) # Screw position on y-axis

  # Standoff variables
  standoff_size: 2.5 # Threaded screw inserts 3.2mm wide, and 3mm tall
  spacer_radius: 2.15 # M2 standoffs
  spacer_diameter: spacer_radius * 2

  # Case variables
  case_x: kx+8 # Case position on x-axis
  case_y: ky+8 # Case position on y-axis

points:
  zones:
    # Main key matrix
    matrix:
      key:
        padding: ky
        spread: kx
        tags:
          - key
          - matrix_key
      anchor.shift: [50,-100] # Fix KiCad placement
      columns:
        outer:
          key:
            column_net: C0
        pinky:
          key:
            column_net: C1
            stagger: 0.1cx
        ring:
          key:
            column_net: C2
            stagger: 0.66cx
        middle:
          key:
            column_net: C3
            stagger: 0.25cx
        index:
          key:
            column_net: C4
            stagger: -0.25cx
        inner:
          key:
            column_net: C5
            stagger: -0.15cx
      rows:
        bottom:
          row_net: R2
        home:
          row_net: R1
        top:
          row_net: R0

    # Thumb cluster
    thumb:
      key:
        padding: ky
        spread: kx
        stagger: 1
        tags:
          - key
          - thumb_key
      anchor:
        ref: matrix_index_bottom
      columns:
        tuck:
          key:
            column_net: C2
            name: thumb_tuck
            shift: [-0.5cx, -1cx]
        layer: 
          key:
            column_net: C3
            name: thumb_layer
            shift: [-0.42cx, -1.22cx]
            rotate: -15
        space:
          key:
            column_net: C4
            name: thumb_space
            width: 1.5kx
            shift: [-0.3cx, -1.4cx]
            rotate: -117
        reach:
          key:
           column_net: C5
           name: thumb_reach
           width: 1.5kx
           shift: [-0.4cx, -2cx]
           rotate: -124
      rows:
        cluster:
          row_net: R3

    # Helper points
    screw_pcb_outer_top:
      key.tags:
        - helper
        - screw
      anchor:
        - ref: matrix_outer_top
          shift: [-screw_x-0.5, screw_y]
    screw_pcb_outer_bottom:
      key.tags:
        - helper
        - screw
      anchor:
        - ref: matrix_outer_bottom
          shift: [-screw_x-0.5, -screw_y]
    screw_pcb_ring_top:
      key.tags:
        - helper
        - screw
      anchor:
        - ref: matrix_ring_top
          shift: [screw_x-2, 0]
    screw_pcb_inner_top:
      key.tags:
        - helper
        - screw
      anchor:
        - ref: matrix_inner_top
          shift: [screw_x+0.5, screw_y]
    screw_pcb_inner_bottom:
      key.tags:
        - helper
        - screw
      anchor:
        - ref: matrix_inner_bottom
          shift: [23.65, -19.5]
    screw_pcb_thumb_tuck:
      key.tags:
        - helper
        - screw
      anchor:
        - ref: thumb_tuck
          shift: [-4.5, 10.75]
  #mirror: &mirror
  #  ref: matrix_inner_top
  #  distance: 5kx
outlines:
    keycap_outline:
    - what: rectangle
      fillet: 2
      where: /key/
      size: [keycw,keych]
    - what: rectangle
      fillet: 2
      where: [thumb_space, thumb_reach]
      size: [1.5kx,ky]
    pcb:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_top
          shift: [-0.6px, 0.5py]
        - ref: matrix_pinky_top
          shift: [-0.5px, 0.7py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.6py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.6py]
        - ref: matrix_middle_top
          shift: [0.5px, 0.6py]
        - ref: matrix_index_top
          shift: [0.5px, 0.6py]         
        - ref: matrix_inner_top
          shift: [0.55px, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px+mcu_padding+mcu_width+0.25, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px+mcu_padding+mcu_width+0.25, -0.5py]
        - ref: matrix_inner_bottom
          shift: [0.5px+mcu_padding+mcu_width+0.25, -0.5py]      
        - ref: thumb_reach
          shift: [-0.9kx, -0.45py]
        - ref: thumb_reach
          shift: [-0.9kx, 0.6py]
        - ref: thumb_reach
          shift: [0.9kx, 0.6py]        
        - ref: thumb_space
          shift: [0.9kx, 0.45py]
        - ref: thumb_space
          shift: [0.9kx, -0.45py]          
        - ref: thumb_layer
          shift: [-0.45px,-0.6py]                    
        - ref: thumb_tuck
          shift: [-0.5px,-0.6py]               
        - ref: matrix_pinky_bottom
          shift: [0.5px,-0.7py]                                      
        - ref: matrix_outer_bottom
          shift: [-0.6px,-0.6py]
    xlBoard:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_top
          shift: [-0.5case_x, 0.5case_y]
        - ref: matrix_pinky_top
          shift: [-0.5case_x, 0.7case_y]
        - ref: matrix_ring_top
          shift: [-0.5case_x, 0.5case_y]
        - ref: matrix_middle_top
          shift: [-0.5case_x, 0.5case_y]
        - ref: matrix_middle_top
          shift: [0.5case_x, 0.5case_y]
        - ref: matrix_index_top
          shift: [0.5case_x, 0.6case_y]
        - ref: matrix_inner_top
          shift: [0.5case_x, 0.5case_y]
        - ref: matrix_inner_top
          shift: [0.5case_x+mcu_padding+mcu_width+0.25, 0.5case_y]
        - ref: matrix_inner_top
          shift: [0.5case_x+mcu_padding+mcu_width+0.25, -0.5case_y]
        - ref: matrix_inner_bottom
          shift: [0.5case_x+mcu_padding+mcu_width+0.25, -0.45case_y]      
        - ref: thumb_reach
          shift: [-0.95kx, 0.5case_y]
        - ref: thumb_reach
          shift: [-0.5case_x, 0.5case_y]
        - ref: thumb_reach
          shift: [0.95kx, 0.5case_y]        
        - ref: thumb_space
          shift: [0.95kx, 0.45case_y]
        - ref: thumb_space
          shift: [0.95kx, -0.45case_y]          
        - ref: thumb_layer
          shift: [-0.4case_x,-0.5case_y]                    
        - ref: thumb_tuck
          shift: [-0.4case_x,-0.5case_y]               
        - ref: matrix_pinky_bottom
          shift: [0.3case_x,-0.6case_y]                                      
        - ref: matrix_outer_bottom
          shift: [-0.5case_x,-0.5case_y]
    mounting: 
    - what: circle
      radius: screw_size
      where: /screw/
    standoff:
    - what: circle
      radius: standoff_size
      where: /screw/
    _combo:
    - what: outline
      name: pcb
    - operation: stack
      name: xlBoard

pcbs:
  scyboard:
    template: kicad8
    outlines:
      main:
        outline: pcb
    footprints:
      key_switches:
        what: ceoloide/switch_choc_v1_v2
        where: /key/
        params:
          from: "{{column_net}}"
          to: "{{colrow}}_B"
          reversible: true
          choc_v2_support: false
        adjust:
          rotate: switch_rotation
      diodes_b:
        what: ceoloide/diode_tht_sod123
        where: /key/
        params:
          from: "{{colrow}}_B"
          to: "{{row_net}}"
          reversible: false
          side: B
        adjust:
          shift: [horizontal_diode_shift, vertical_diode_shift]
          rotate: 90 + diode_rotation       
      diodes_f:
        what: ceoloide/diode_tht_sod123
        where: /key/
        params:
          from: "{{colrow}}_B"
          to: "{{row_net}}"
          reversible: false
          side: F
        adjust:
          shift: [-1 * horizontal_diode_shift, vertical_diode_shift]
          rotate: 90 + diode_rotation    
      mcu:
        what: ceoloide/mcu_nice_nano
        where:
          ref: matrix_inner_top
          shift: [kx+mcu_padding, -mcu_width/2+1.875]
        params:
          P0: DAT
          P1: LED
          P21: C0
          P20: C1
          P19: C2
          P18: C3
          P15: C4
          P14: C5
          P2: SDA
          P3: SCL
          P4: CS
          P5: R0
          P6: R1
          P7: R2
          P8: R3
          reversible: true
          show_silk_labels: true
          show_via_labels: true
          show_instructions: false
      on_off_switch:
        what: ceoloide/power_switch_smd_side
        where: matrix_inner_top
        params:
          from: BAT_P
          to: RAW
          reversible: true
        adjust:
          shift: [pwr_x, pwr_y]
      reset_switch:
        what: ceoloide/reset_switch_smd_side
        where: matrix_inner_top
        params:
          from: GND
          to: RST
          reversible: true
          include_bosses: true
        adjust:
          shift: [rst_x, rst_y]    
      battery_connector:  
        what: ceoloide/battery_connector_jst_ph_2
        where: matrix_inner_top
        params:
          BAT_P: BAT_P
          BAT_N: GND
          reversible: true
          include_courtyard: false
        adjust:
          shift: [jst_x, jst_y]
          rotate: 90
      screw_holes:
        what: ceoloide/mounting_hole_npth
        where: /screw_pcb/
        params:
          hole_size: spacer_diameter
          hole_drill: spacer_diameter
cases:
  bottom:
    - name: pcb
      extrude: 1
  xlBottom:
    - name: xlBoard
      extrude: 1
  _outerWall:
    - name: xlBoard
      extrude: 4
  _innerWall:
    - name: pcb
      extrude: 4
  wall:
    - what: case
      name: _outerWall
      operation: add
    - what: case
      name: _innerWall
      operation: subtract
  _holes:
    - name: mounting
      extrude: 4
  _standoffs:
    - name: standoff
      extrude: 4
  bottom_case:
    - what: case
      name: xlBottom
      operation: add
    - what: case
      name: wall
      operation: add
    - what: case
      name: _standoffs
      operation: add
    - what: case
      name: _holes
      operation: subtract
