meta:
  engine: 4.1.0
  name: scyboard
  version: 1.0
  author: Scybin
  url: https://github.com/Scybin/scyboard

units:

  # Key Variables
  kx: cx # 18 mm width
  ky: cy # 17 mm height
  px: kx + 2 # horizontal padding (20mm)
  py: ky + 2 # vertical padding (19mm)
  ks: 18.5 # horizontal space between columns (default: 19)
  kp: 17.5 # vertical padding between keys (deafult: 19)
  kcow: 13.8 # key cutout hole width
  kcoh: 13.8 # key cutout hole height
  keycw: 17.5 # keycap width (cherry: 18, choc: 17.5)
  keych: 16.5 # keycap height (cherry: 18, choc: 16.5)  
  vertical_diode_shift: 1.5 # How much to shift to avoid overlap
  horizontal_diode_shift: -0.5 kcow - 0.85
  diode_rotation: -180 # Diode rotation
  switch_rotation: 180 # Hotswap south, led north

  # Controller Variables
  mcu_height: 33
  mcu_width: 18
  mcu_padding: 1.5

  # JST Variables
  jst_x: 20.35
  jst_y: -34.01
  jst_shift: 3.5

  # Reset Switch Variables
  rst_x: 27.884
  rst_y: -28.5

  # On Off Switch Variables
  pwr_x: 28.25
  pwr_y: rst_y-9.35

  # Physical measures
  screw_radius: 1.1 # M2 screws
  screw_diameter: screw_radius * 2
  screw_head_radius: 2.05
  screw_head_diameter: screw_head_radius * 2
  spacer_radius: 2.15 # M2 standoffs
  spacer_diameter: spacer_radius * 2
  fillet_radius: 0.5
  pwr_trace_width: 0.25
  gnd_trace_width: 0.25
  signal_trace_width: 0.15
  via_size: 0.56 # JLCPCB min 0.56 | KiCad default 0.8
  via_drill: 0.3 # JLCPCB min 0.3 | KiCad default 0.4

points:
  zones:
    # Main key matrix
    matrix:
      key:
        padding: ky
        spread: kx
      anchor.shift: [50,-100] # Fix KiCad placement
      columns:
        outer:
          key:
            column_net: C0
        pinky:
          key:
            column_net: C1
            stagger: 0.1cx
        ring:
          key:
            column_net: C2
            stagger: 0.66cx
        middle:
          key:
            column_net: C3
            stagger: 0.25cx
        index:
          key:
            column_net: C4
            stagger: -0.25cx
        inner:
          key:
            column_net: C5
            stagger: -0.15cx
      rows:
        bottom:
          row_net: R2
        home:
          row_net: R1
        top:
          row_net: R0

    # Thumb cluster
    thumb:
      key:
        padding: ky
        spread: kx
        stagger: 1
      anchor:
        ref: matrix_index_bottom
      columns:
        tuck:
          key:
            column_net: C2
            name: thumb_tuck
            shift: [-0.5cx, -1cx]
        layer: 
          key:
            column_net: C3
            name: thumb_layer
            shift: [-0.42cx, -1.22cx]
            rotate: -15
        space:
          key:
            column_net: C4
            name: thumb_space
            width: 1.5kx
            shift: [-0.3cx, -1.4cx]
            rotate: -117
        reach:
          key:
           column_net: C5
           name: thumb_reach
           width: 1.5kx
           shift: [-0.4cx, -2cx]
           rotate: -124
      rows:
        cluster:
          row_net: R3

    # Helper points
    screw_pcb_left_top:
      key.tags:
        - helper
        - screw
      anchor:
        - ref: matrix_outer_top
          shift: [9, -8.5]

outlines:
    keycap_outline:
    - what: rectangle
      fillet: 2
      where: true
      size: [keycw,keych]
    - what: rectangle
      fillet: 2
      where: [thumb_space, thumb_reach]
      size: [1.5kx,ky]
    pcb:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_top
          shift: [-0.5px, 0.7py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [0.5px, 0.5py]
        - ref: matrix_index_top
          shift: [0.5px, 0.6py]
        - ref: matrix_inner_top
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px+mcu_padding+mcu_width+0.25, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px+mcu_padding+mcu_width+0.25, -0.5py]
        - ref: matrix_inner_bottom
          shift: [0.5px+mcu_padding+mcu_width+0.25, -0.5py]      
        - ref: thumb_reach
          shift: [-0.8kx, -0.45py]
        - ref: thumb_reach
          shift: [-0.8kx, 0.5py]
        - ref: thumb_reach
          shift: [0.8kx, 0.5py]        
        - ref: thumb_space
          shift: [0.8kx, 0.45py]
        - ref: thumb_space
          shift: [0.8kx, -0.45py]          
        - ref: thumb_layer
          shift: [-0.45px,-0.5py]                    
        - ref: thumb_tuck
          shift: [-0.5px,-0.5py]               
        - ref: matrix_pinky_bottom
          shift: [0.5px,-0.6py]                                      
        - ref: matrix_outer_bottom
          shift: [-0.5px,-0.5py]
    _combo:
    - what: outline
      name: pcb
    - operation: subtract
      name: keycap_outline
pcbs:
  scyboard:
    template: kicad8
    outlines:
      main:
        outline: pcb
    footprints:
      key_switches_b:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          hotswap: true
          reversible: false
          from: "{{column_net}}"
          to: "{{colrow}}_B"
          side: B
        adjust:
          rotate: switch_rotation
      diodes_b:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}_B"
          to: "{{row_net}}"
          include_tht: false
          reversible: false
          side: B
        adjust:
          shift: [horizontal_diode_shift,vertical_diode_shift]
          rotate: 90 + diode_rotation       
      mcu:
        what: ceoloide/mcu_nice_nano
        where:
          ref: matrix_inner_top
          shift: [kx+mcu_padding, -mcu_width/2+1.875]
        params:
          P0: DAT
          P1: LED
          P21: C0
          P20: C1
          P19: C2
          P18: C3
          P15: C4
          P14: C5
          P2: SDA
          P3: SCL
          P4: CS
          P5: R0
          P6: R1
          P7: R2
          P8: R3
          reverse_mount: true
          show_silk_labels: true
          show_via_labels: true
          show_instructions: false
      on_off_switch:
        what: ceoloide/power_switch_smd_side
        where: matrix_inner_top
        params:
          from: BAT_P
          to: RAW
          reversible: false
        adjust:
          shift: [1.5 ks -0.5+1, pwr_y]
      reset_switch:
        what: ceoloide/reset_switch_smd_side
        where: matrix_inner_top
        params:
          from: GND
          to: RST
          reversible: false
          include_bosses: true
        adjust:
          shift: [rst_x, rst_y]    
      battery_connector:  
        what: ceoloide/battery_connector_jst_ph_2
        where: matrix_inner_top
        params:
          BAT_P: BAT_P
          BAT_N: GND
          reversible: false
          include_courtyard: false
        adjust:
          shift: [jst_x+jst_shift, jst_y]
          rotate: 90
      hole_top_left:
        what: ceoloide/mounting_hole_npth
        where: /screw_pcb/
        params:
          hole_size: spacer_diameter
          hole_drill: spacer_diameter
